#!/bin/bash
export NUM_THREADS=18
export OMP_NUM_THREADS=$NUM_THREADS
export OPENBLAS_NUM_THREADS=$NUM_THREADS
export MKL_NUM_THREADS=$NUM_THREADS
export VECLIB_MAXIMUM_THREADS=$NUM_THREADS
export NUMEXPR_NUM_THREADS=$NUM_THREADS
python3 sherpa.py "$@"
